# Generated by Django 3.1.3 on 2023-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=70)),
                ('lecturerName', models.CharField(max_length=70)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
