# Generated by Django 3.1.3 on 2023-01-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230119_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='matricNo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
    ]
