# Generated by Django 3.1.3 on 2023-01-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230119_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shift',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], default='Student', max_length=20, null=True),
        ),
    ]
