# Generated by Django 3.1.3 on 2023-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230119_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastface',
            name='date',
            field=models.DateField(),
        ),
    ]
